name: Build CI

on: [push]

jobs:
  make-testing:
    name: Consistency testing Go code
    runs-on: ubuntu-latest
    steps:
      - name: Building project
        uses: ./.github/actions/build

      - name: Test
        run: go test -v ./...
